<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AmtPtpConfigGui</RootNamespace>
    <AssemblyName>AmtPtpConfigGui</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;ARM64</Platforms>
    <SatelliteResourceLanguages>uk;en</SatelliteResourceLanguages>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DebugType>none</DebugType>
    <PublishReadyToRun>false</PublishReadyToRun>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

</Project>