// Device.c - Device handling events. Kernel-mode Driver Framework

#include "driver.h"
#include "device.tmh"
#include "Match.h" // MATCH_MAX_TIME_DELTA_100NS, for the D0Entry tick-cache
#include <wdmsec.h> // WdfDeviceInitAssignSDDLString / SDDL_DEVOBJ_* - link Wdmsec.lib

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, AmtPtpDeviceUsbKmCreateDevice)
#pragma alloc_text (PAGE, AmtPtpDeviceUsbKmEvtDevicePrepareHardware)
// Both PASSIVE_LEVEL-only and both already call PAGED_CODE(); previously
// missing here, which left them PAGED_CODE()-asserting from a non-paged
// segment (PREfast C28172).
#pragma alloc_text (PAGE, AmtPtpEvtDeviceD0Exit)
#pragma alloc_text (PAGE, SelectInterruptInterface)
#endif

#define ACTIVE_CONTACTS_ALIGNMENT 64
#define ACTIVE_CONTACTS_POOL_TAG  'ApAc' // "AmtPtp Active Contacts"

// Allocates the ActiveContacts pool on a real 64-byte boundary. 
static PACTIVE_CONTACT
AmtAllocateAlignedContactPool(VOID)
{
    SIZE_T    rawSize;
    PVOID     raw;
    ULONG_PTR aligned;

    rawSize = (MAX_CONTACTS * sizeof(ACTIVE_CONTACT)) + ACTIVE_CONTACTS_ALIGNMENT + sizeof(PVOID);

    raw = ExAllocatePoolZero(NonPagedPoolNx, rawSize, ACTIVE_CONTACTS_POOL_TAG);
    if (raw == NULL) {
        return NULL;
    }

    aligned = ((ULONG_PTR)raw + sizeof(PVOID) + (ACTIVE_CONTACTS_ALIGNMENT - 1))
              & ~(ULONG_PTR)(ACTIVE_CONTACTS_ALIGNMENT - 1);

    *((PVOID*)(aligned - sizeof(PVOID))) = raw;

    return (PACTIVE_CONTACT)aligned;
}

static VOID
AmtFreeAlignedContactPool(_In_opt_ PACTIVE_CONTACT Pool)
{
    PVOID raw;

    if (Pool == NULL) {
        return;
    }

    raw = *((PVOID*)((ULONG_PTR)Pool - sizeof(PVOID)));
    ExFreePoolWithTag(raw, ACTIVE_CONTACTS_POOL_TAG);
}

// Read the matching config entry for the detected device.
//
// DESIGN NOTE: an idProduct with no table entry is a deliberate best-effort
// fallback to Bcm5974ConfigTable[0] (a TYPE4/T2 profile), not an error -
// this lets the driver still bind (with possibly miscalibrated geometry
// limits) on unlisted-but-compatible hardware instead of refusing to load.
// If that's no longer the desired behavior, change this to return NULL and
// have AmtPtpDeviceUsbKmEvtDevicePrepareHardware fail the bind instead.
_IRQL_requires_(PASSIVE_LEVEL)
static const struct BCM5974_CONFIG*
AmtPtpGetDeviceConfig(_In_ const PUSB_DEVICE_DESCRIPTOR DeviceDescriptor)
{
    USHORT id = DeviceDescriptor->idProduct;
    const struct BCM5974_CONFIG* cfg;

    for (cfg = Bcm5974ConfigTable; cfg->identification; ++cfg) {
        if (cfg->identification == id)
            return cfg;
    }

    return &Bcm5974ConfigTable[0];
}

// AmtPtpDeviceUsbKmCreateDevice

NTSTATUS
AmtPtpDeviceUsbKmCreateDevice(_Inout_ PWDFDEVICE_INIT DeviceInit)
{
    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks;
    WDF_OBJECT_ATTRIBUTES        deviceAttributes;
    PDEVICE_CONTEXT              deviceContext;
    WDFDEVICE                    device;
    NTSTATUS                     status;

    PAGED_CODE();

    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);
    pnpPowerCallbacks.EvtDevicePrepareHardware = AmtPtpDeviceUsbKmEvtDevicePrepareHardware;
    pnpPowerCallbacks.EvtDeviceD0Entry         = AmtPtpEvtDeviceD0Entry;
    pnpPowerCallbacks.EvtDeviceD0Exit          = AmtPtpEvtDeviceD0Exit;
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);
    deviceAttributes.EvtCleanupCallback = AmtPtpEvtDeviceContextCleanup;

    // Explicit security descriptor for our custom device interface
    // (GUID_DEVINTERFACE_AmtPtpDeviceUsbKm). We're a lower filter on the
    // HIDClass stack, so by default the OS gates access to *our* device
    // interface using the underlying PDO's security descriptor (owned by
    // the USB stack, not us) - not the FDO's. HIDClass PDOs get a locked-
    // down default (anti-keylogging hardening), so without this call
    // CreateFile() on our interface fails with ACCESS_DENIED even for an
    // elevated Administrator. WdfDeviceInitAssignSDDLString overrides that
    // default and makes the ACL below the actual authority for our
    // interface. Grants SYSTEM + Administrators + any authenticated user
    // (AmtPtpConfigGui runs "asInvoker", i.e. as a normal, non-elevated
    // user - it must be able to open the handle without UAC prompts).
    // Requires a named device object, hence AssignName before AssignSDDL;
    // NULL requests an autogenerated name since we don't need a specific
    // symbolic device name of our own (only the device *interface* path
    // is used by the GUI, via SetupDi, not this name directly).
    status = WdfDeviceInitAssignName(DeviceInit, NULL);
    if (!NT_SUCCESS(status))
        return status;

    {
        DECLARE_CONST_UNICODE_STRING(sddl,
            L"D:P(A;;GA;;;SY)(A;;GA;;;BA)(A;;GA;;;AU)");
            // SY = LocalSystem, BA = Administrators, AU = Authenticated Users

        status = WdfDeviceInitAssignSDDLString(DeviceInit, &sddl);
        if (!NT_SUCCESS(status))
            return status;
    }

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);
    if (!NT_SUCCESS(status))
        return status;

    deviceContext = DeviceGetContext(device);
    RtlZeroMemory(deviceContext, sizeof(DEVICE_CONTEXT));

    deviceContext->ActiveContacts = AmtAllocateAlignedContactPool();
    if (deviceContext->ActiveContacts == NULL) {
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    deviceContext->PtpReportButton = TRUE;
    deviceContext->PtpReportTouch  = TRUE;

    // Palm-rejection config: compiled-in defaults first (so the device is
    // always in a valid state even if registry access below fails), then
    // best-effort overridden from the registry if a GUI previously saved
    // custom values there.
    {
        AMT_PALM_CONFIG defaultCfg = AMT_PALM_CONFIG_DEFAULT_INIT;
        deviceContext->PalmConfig = defaultCfg;
    }
    AmtPalmConfigLoadFromRegistry(device, &deviceContext->PalmConfig);

    // Create the shared state lock for frame processing.
    {
        WDF_OBJECT_ATTRIBUTES lockAttributes;
        WDF_OBJECT_ATTRIBUTES_INIT(&lockAttributes);
        lockAttributes.ParentObject = device;

        status = WdfSpinLockCreate(&lockAttributes, &deviceContext->StateLock);
        if (!NT_SUCCESS(status)) {
            return status;
        }
    }

    status = WdfDeviceCreateDeviceInterface(
        device, &GUID_DEVINTERFACE_AmtPtpDeviceUsbKm, NULL);

    if (NT_SUCCESS(status))
        status = AmtPtpDeviceUsbKmQueueInitialize(device);

    return status;
}

// AmtPtpDeviceUsbKmEvtDevicePrepareHardware

NTSTATUS
AmtPtpDeviceUsbKmEvtDevicePrepareHardware(
    _In_ WDFDEVICE     Device,
    _In_ WDFCMRESLIST  ResourceList,
    _In_ WDFCMRESLIST  ResourceListTranslated)
{
    NTSTATUS         status;
    PDEVICE_CONTEXT  pDeviceContext;
    WDF_USB_DEVICE_INFORMATION deviceInfo;

    UNREFERENCED_PARAMETER(ResourceList);
    UNREFERENCED_PARAMETER(ResourceListTranslated);
    PAGED_CODE();

    pDeviceContext = DeviceGetContext(Device);

    if (pDeviceContext->UsbDevice == NULL) {
        status = WdfUsbTargetDeviceCreate(
            Device, WDF_NO_OBJECT_ATTRIBUTES, &pDeviceContext->UsbDevice);
        if (!NT_SUCCESS(status)) {
            return status;
        }
    }

    WdfUsbTargetDeviceGetDeviceDescriptor(
        pDeviceContext->UsbDevice, &pDeviceContext->DeviceDescriptor);

    pDeviceContext->DeviceInfo = AmtPtpGetDeviceConfig(&pDeviceContext->DeviceDescriptor);
    if (pDeviceContext->DeviceInfo == NULL) {
        return STATUS_INVALID_DEVICE_STATE;
    }

    // Only TYPE4/TYPE5 packets carry a real pressure field (see
    // AppleDefinition.h - pressure was introduced with TYPE4). Everything
    // older (TYPE1-3, e.g. WELLSPRING8) reports zeros there, so treat those
    // trackpads as force-touch-incapable rather than let stale/zero
    // pressure feed the arbitration state machine.
    pDeviceContext->SupportsForceTouch =
        (pDeviceContext->DeviceInfo->tp_type == TYPE4) ||
        (pDeviceContext->DeviceInfo->tp_type == TYPE5);

    WDF_USB_DEVICE_INFORMATION_INIT(&deviceInfo);
    status = WdfUsbTargetDeviceRetrieveInformation(pDeviceContext->UsbDevice, &deviceInfo);
    if (NT_SUCCESS(status)) {

        pDeviceContext->UsbDeviceTraits = deviceInfo.Traits;
    } else {
        pDeviceContext->UsbDeviceTraits = 0;
    }

    status = SelectInterruptInterface(Device);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    status = AmtPtpConfigContReaderForInterruptEndPoint(pDeviceContext);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    pDeviceContext->PtpReportButton = TRUE;
    pDeviceContext->PtpReportTouch  = TRUE;

    return status;
}

// AmtPtpEvtDeviceD0Entry

NTSTATUS
AmtPtpEvtDeviceD0Entry(
    _In_ WDFDEVICE              Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState)
{
    PDEVICE_CONTEXT pDeviceContext;
    NTSTATUS        status;
    BOOLEAN         isTargetStarted;

    UNREFERENCED_PARAMETER(PreviousState);

    pDeviceContext  = DeviceGetContext(Device);
    isTargetStarted = FALSE;

    pDeviceContext->LastReportTime =
        KeQueryPerformanceCounter(&pDeviceContext->PerfFrequency);

    // MICRO-OPT: precompute PerfFrequency-derived tick thresholds once here
    // instead of on every call site (see Device.h field comments). 0 when
    // there's no usable clock, matching each site's original PerfFrequencyHz
    // <= 0 guard exactly.
    if (pDeviceContext->PerfFrequency.QuadPart > 0) {
        pDeviceContext->RetapWindowTicks =
            (RETAP_WINDOW_100NS * pDeviceContext->PerfFrequency.QuadPart) / 10000000LL;
        pDeviceContext->MatchMaxTimeDeltaTicks =
            (MATCH_MAX_TIME_DELTA_100NS * pDeviceContext->PerfFrequency.QuadPart) / 10000000LL;
        pDeviceContext->ClickArbitrationTimeoutTicks =
            (pDeviceContext->PerfFrequency.QuadPart * CLICK_ARBITRATION_TIMEOUT_MS) / 1000;
        pDeviceContext->ScanTimeScaleQ16 =
            (10000LL << 16) / pDeviceContext->PerfFrequency.QuadPart;
    } else {
        pDeviceContext->RetapWindowTicks             = 0;
        pDeviceContext->MatchMaxTimeDeltaTicks        = 0;
        pDeviceContext->ClickArbitrationTimeoutTicks = 0;

        // OPTIMIZATION: fold the "no usable clock" fallback into the same
        // Q16 scale used by the normal path, instead of branching on
        // PerfFrequency on every single interrupt completion (see
        // AmtPtpEvtUsbInterruptPipeReadComplete). The old fallback did
        // "PerfDelta /= 100LL"; solving (x*scale)>>16 == x/100 for scale
        // gives 65536/100 = 655.36, rounded to 655 - same approximation,
        // computed once here instead of re-branched every completion. This
        // path is already the degenerate "no usable clock" case, so the
        // extra ~0.05% rounding difference from 655 vs 655.36 is moot.
        pDeviceContext->ScanTimeScaleQ16             = 655;
    }

    // Reset per-session timing and contact state on D0 entry.
    pDeviceContext->ScanTimeAccumulator = 0;
    pDeviceContext->NextContactId        = 0;
    pDeviceContext->OverflowCount        = 0;
    pDeviceContext->PrevButtonClicked    = FALSE;
    pDeviceContext->ForceTouchAnchorValid = FALSE;
    pDeviceContext->ForceTouchDragLockout = FALSE;
    // Drop pending/in-flight force-touch clicks from the previous power
    // session - nothing was delivered to a live HID client across a D0
    // transition, so there's no in-flight UP to worry about orphaning.
    pDeviceContext->ForceTouchDeliveryState     = FORCE_TOUCH_DELIVERY_IDLE;
    pDeviceContext->PendingForceTouchClickCount = 0;
    pDeviceContext->ClickArbitrationState = CLICK_ARBITRATION_IDLE;
    AmtContactPoolInit(pDeviceContext->ActiveContacts);

    // Zero RecentLifts on D0Entry to prevent stale retap-smoothing
    // hints from a previous power session.
    RtlZeroMemory(&pDeviceContext->RecentLifts, sizeof(pDeviceContext->RecentLifts));

    // Wellspring-mode setup is best-effort; only the start result matters.
    (VOID)AmtPtpSetWellspringMode(pDeviceContext, TRUE);

    status = WdfIoTargetStart(
        WdfUsbTargetPipeGetIoTarget(pDeviceContext->InterruptPipe));
    if (!NT_SUCCESS(status)) {
        goto end;
    }
    isTargetStarted = TRUE;

end:
    if (!NT_SUCCESS(status) && isTargetStarted) {
        WdfIoTargetStop(
            WdfUsbTargetPipeGetIoTarget(pDeviceContext->InterruptPipe),
            WdfIoTargetCancelSentIo);
    }

    return status;
}

// AmtPtpEvtDeviceD0Exit

NTSTATUS
AmtPtpEvtDeviceD0Exit(
    _In_ WDFDEVICE              Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState)
{
    PDEVICE_CONTEXT pDeviceContext;

    UNREFERENCED_PARAMETER(TargetState);
    PAGED_CODE();

    pDeviceContext = DeviceGetContext(Device);

    WdfIoTargetStop(
        WdfUsbTargetPipeGetIoTarget(pDeviceContext->InterruptPipe),
        WdfIoTargetCancelSentIo);

    AmtPtpSetWellspringMode(pDeviceContext, FALSE);

    return STATUS_SUCCESS;
}

// AmtPtpEvtDeviceContextCleanup
// Frees the manually-aligned ActiveContacts pool allocated in AmtPtpDeviceUsbKmCreateDevice. 

VOID
AmtPtpEvtDeviceContextCleanup(
    _In_ WDFOBJECT Device)
{
    PDEVICE_CONTEXT pDeviceContext;
    pDeviceContext = DeviceGetContext((WDFDEVICE)Device);

    AmtFreeAlignedContactPool(pDeviceContext->ActiveContacts);
    pDeviceContext->ActiveContacts = NULL;
}

// SelectInterruptInterface

_IRQL_requires_(PASSIVE_LEVEL)
NTSTATUS
SelectInterruptInterface(_In_ WDFDEVICE Device)
{
    WDF_USB_DEVICE_SELECT_CONFIG_PARAMS configParams;
    NTSTATUS                            status = STATUS_SUCCESS;
    PDEVICE_CONTEXT                     pDeviceContext;
    WDFUSBPIPE                          pipe;
    WDF_USB_PIPE_INFORMATION            pipeInfo;
    UCHAR                               index;
    UCHAR                               numberConfiguredPipes;

    PAGED_CODE();

    pDeviceContext = DeviceGetContext(Device);
    WDF_USB_DEVICE_SELECT_CONFIG_PARAMS_INIT_SINGLE_INTERFACE(&configParams);

    status = WdfUsbTargetDeviceSelectConfig(
        pDeviceContext->UsbDevice, WDF_NO_OBJECT_ATTRIBUTES, &configParams);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    pDeviceContext->UsbInterface = configParams.Types.SingleInterface.ConfiguredUsbInterface;
    numberConfiguredPipes        = configParams.Types.SingleInterface.NumberConfiguredPipes;

    for (index = 0; index < numberConfiguredPipes; index++) {
        WDF_USB_PIPE_INFORMATION_INIT(&pipeInfo);
        pipe = WdfUsbInterfaceGetConfiguredPipe(
            pDeviceContext->UsbInterface, index, &pipeInfo);

        WdfUsbTargetPipeSetNoMaximumPacketSizeCheck(pipe);

        if (WdfUsbPipeTypeInterrupt == pipeInfo.PipeType) {
            pDeviceContext->InterruptPipe = pipe;
            break;
        }
    }

    if (!pDeviceContext->InterruptPipe) {
        return STATUS_INVALID_DEVICE_STATE;
    }

    return STATUS_SUCCESS;
}

// AmtPtpSetWellspringMode

_IRQL_requires_(PASSIVE_LEVEL)
NTSTATUS
AmtPtpSetWellspringMode(
    _In_ PDEVICE_CONTEXT DeviceContext,
    _In_ BOOLEAN         IsWellspringModeOn)
{
    NTSTATUS                    status;
    WDF_USB_CONTROL_SETUP_PACKET setupPacket;
    WDF_MEMORY_DESCRIPTOR       memoryDescriptor;
    WDF_REQUEST_SEND_OPTIONS    sendOptions;
    ULONG                       cbTransferred;
    // OPTIMIZATION: um_size is at most 8 bytes across every USBMSG_TYPEn
    // table entry (statically guaranteed by the C_ASSERT block next to
    // those defines in AppleDefinition.h) - a WdfMemoryCreate/WdfObjectDelete
    // pool round-trip for this was unnecessary overhead and an extra
    // failure path for what's really just a few bytes on the stack.
    UCHAR                       buffer[8] = { 0 };

    // AUDIT FIX: bound both control transfers below so a stalled device/hub
    // can't hang the calling thread (this runs on the D0Entry path) forever.
    WDF_REQUEST_SEND_OPTIONS_INIT(&sendOptions, WDF_REQUEST_SEND_OPTION_TIMEOUT);
    WDF_REQUEST_SEND_OPTIONS_SET_TIMEOUT(
        &sendOptions, WDF_REL_TIMEOUT_IN_SEC(WELLSPRING_CONTROL_TRANSFER_TIMEOUT_SEC));

    // TYPE3 devices (WELLSPRING8 - MacBookAir6,x/7,x, 2013-2017) stream
    // multitouch data without a vendor mode switch - matches Linux
    // bcm5974_wellspring_mode(): "Type 3 does not require a mode switch".
    // Every T2 entry (TYPE4) still falls through to the read/modify/write
    // sequence below as before.
    if (DeviceContext->DeviceInfo->tp_type == TYPE3) {
        DeviceContext->IsWellspringModeOn = IsWellspringModeOn;
        return STATUS_SUCCESS;
    }

    NT_ASSERT(DeviceContext->DeviceInfo->um_size <= sizeof(buffer));

    WDF_MEMORY_DESCRIPTOR_INIT_BUFFER(
        &memoryDescriptor, buffer, (ULONG)DeviceContext->DeviceInfo->um_size);

    WDF_USB_CONTROL_SETUP_PACKET_INIT(
        &setupPacket,
        BmRequestDeviceToHost, BmRequestToInterface,
        BCM5974_WELLSPRING_MODE_READ_REQUEST_ID,
        (USHORT)DeviceContext->DeviceInfo->um_req_val,
        (USHORT)DeviceContext->DeviceInfo->um_req_idx);
    setupPacket.Packet.bm.Request.Type = BmRequestClass;

    status = WdfUsbTargetDeviceSendControlTransferSynchronously(
        DeviceContext->UsbDevice, WDF_NO_HANDLE, &sendOptions,
        &setupPacket, &memoryDescriptor, &cbTransferred);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    buffer[DeviceContext->DeviceInfo->um_switch_idx] = IsWellspringModeOn
        ? (unsigned char)DeviceContext->DeviceInfo->um_switch_on
        : (unsigned char)DeviceContext->DeviceInfo->um_switch_off;

    WDF_USB_CONTROL_SETUP_PACKET_INIT(
        &setupPacket,
        BmRequestHostToDevice, BmRequestToInterface,
        BCM5974_WELLSPRING_MODE_WRITE_REQUEST_ID,
        (USHORT)DeviceContext->DeviceInfo->um_req_val,
        (USHORT)DeviceContext->DeviceInfo->um_req_idx);
    setupPacket.Packet.bm.Request.Type = BmRequestClass;

    status = WdfUsbTargetDeviceSendControlTransferSynchronously(
        DeviceContext->UsbDevice, WDF_NO_HANDLE, &sendOptions,
        &setupPacket, &memoryDescriptor, &cbTransferred);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    DeviceContext->IsWellspringModeOn = IsWellspringModeOn;

    return status;
}